#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0

# `deploy/k8s/gen-secrets.sh` — the K8s equivalent of `infra/setup.sh`'s .env
# scaffolding: write-once, never regenerates a value that's already there, generates a fresh
# strong value for every field `base/secret.example.yaml` ships as `REPLACE_ME`. Produces
# `deploy/k8s/base/secret.yaml` (gitignored — never commit it; `base/kustomization.yaml`
# references it by that exact filename, so `kubectl apply -k` fails loudly if this script hasn't
# been run yet, by design).
#
# Same hex-not-base64 reasoning infra/setup.sh's own comment documents: every service
# builds its Postgres DSN as a plain `fmt.Sprintf("postgres://%s:%s@host:port/db", ...)` with no
# URL-encoding anywhere in the Go tree, so a generated secret containing `/` or `+` breaks DSN
# parsing outright. `openssl rand -hex 24` output is never URL-meaningful.
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
example_file="$script_dir/base/secret.example.yaml"
out_file="$script_dir/base/secret.yaml"

log() { echo "[gen-secrets] $*" >&2; }

if [ ! -f "$example_file" ]; then
  echo "[gen-secrets] FAIL: $example_file not found" >&2
  exit 1
fi

if [ -f "$out_file" ]; then
  log "$out_file already exists — leaving every value exactly as-is (write-once; never regenerated)"
  log "delete it yourself first if you really want a fresh secret set (e.g. after a full cluster teardown)"
  exit 0
fi

log "generating $out_file from $example_file's field list"

# Every stringData key in the example file, in order, except the apiVersion/kind/metadata scaffold
# — grabs each `KEY: "REPLACE_ME"` line under `stringData:` and re-emits it with a fresh value.
{
  echo "# Generated by deploy/k8s/gen-secrets.sh — DO NOT COMMIT (gitignored)."
  echo "# Real credentials. Re-run gen-secrets.sh only after deleting this file on purpose."
  echo "apiVersion: v1"
  echo "kind: Secret"
  echo "metadata:"
  echo "  name: kiban-secrets"
  echo "type: Opaque"
  echo "stringData:"
  while IFS= read -r key; do
    value="$(openssl rand -hex 24)"
    echo "  ${key}: \"${value}\""
    log "generated ${key}"
  done < <(sed -n 's/^  \([A-Za-z0-9_-]*\): "REPLACE_ME"$/\1/p' "$example_file")
} > "$out_file"

chmod 600 "$out_file"
log "done — $out_file written (0600). Apply with: kubectl apply -k deploy/k8s/overlays/<kind|production>"
