// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package org

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditIdentityEvent struct {
	ID            int64              `json:"id"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	Actor         string             `json:"actor"`
	Action        string             `json:"action"`
	Subject       string             `json:"subject"`
	Payload       []byte             `json:"payload"`
	CorrelationID *string            `json:"correlation_id"`
}

type AuditOrgEvent struct {
	ID            int64              `json:"id"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	Actor         string             `json:"actor"`
	Action        string             `json:"action"`
	Subject       string             `json:"subject"`
	Payload       []byte             `json:"payload"`
	CorrelationID *string            `json:"correlation_id"`
}

type IdentityMfaPolicy struct {
	ID        pgtype.UUID        `json:"id"`
	Scope     string             `json:"scope"`
	SubjectID pgtype.UUID        `json:"subject_id"`
	Required  bool               `json:"required"`
	Method    *string            `json:"method"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type IdentityUserAccount struct {
	ID                pgtype.UUID        `json:"id"`
	KcSub             string             `json:"kc_sub"`
	Email             *string            `json:"email"`
	PreferredUsername *string            `json:"preferred_username"`
	Lifecycle         string             `json:"lifecycle"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type IdentityUserLoginObservation struct {
	UserID      pgtype.UUID        `json:"user_id"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	LastLoginIp *string            `json:"last_login_ip"`
}

type IdentityUserReadV struct {
	ID                pgtype.UUID `json:"id"`
	KcSub             string      `json:"kc_sub"`
	Email             *string     `json:"email"`
	PreferredUsername *string     `json:"preferred_username"`
	Lifecycle         string      `json:"lifecycle"`
}

type OrgGroup struct {
	ID          pgtype.UUID        `json:"id"`
	CompanyID   pgtype.UUID        `json:"company_id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Source      string             `json:"source"`
	ExternalRef *string            `json:"external_ref"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type OrgGroupMember struct {
	GroupID  pgtype.UUID        `json:"group_id"`
	MemberID pgtype.UUID        `json:"member_id"`
	AddedBy  string             `json:"added_by"`
	AddedAt  pgtype.Timestamptz `json:"added_at"`
}

type OrgMember struct {
	ID          pgtype.UUID `json:"id"`
	CompanyID   pgtype.UUID `json:"company_id"`
	Code        string      `json:"code"`
	DisplayName string      `json:"display_name"`
	Email       *string     `json:"email"`
	UserID      pgtype.UUID `json:"user_id"`
	IsActive    bool        `json:"is_active"`
}

type OrgOrgUnit struct {
	ID       pgtype.UUID `json:"id"`
	TypeKey  string      `json:"type_key"`
	ParentID pgtype.UUID `json:"parent_id"`
	Code     string      `json:"code"`
	Name     string      `json:"name"`
	IsActive bool        `json:"is_active"`
}

type OrgOrgUnitType struct {
	Key       string `json:"key"`
	Label     string `json:"label"`
	IsCompany bool   `json:"is_company"`
}

type OrgPosition struct {
	ID        pgtype.UUID `json:"id"`
	CompanyID pgtype.UUID `json:"company_id"`
	Code      string      `json:"code"`
	Title     string      `json:"title"`
	OrgUnitID pgtype.UUID `json:"org_unit_id"`
}

type OrgPositionAssignment struct {
	ID         pgtype.UUID `json:"id"`
	PositionID pgtype.UUID `json:"position_id"`
	MemberID   pgtype.UUID `json:"member_id"`
	ValidFrom  pgtype.Date `json:"valid_from"`
	ValidTo    pgtype.Date `json:"valid_to"`
}
