// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package org

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupMember = `-- name: AddGroupMember :execrows
INSERT INTO org.group_member (group_id, member_id, added_by)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddGroupMemberParams struct {
	GroupID  pgtype.UUID `json:"group_id"`
	MemberID pgtype.UUID `json:"member_id"`
	AddedBy  string      `json:"added_by"`
}

// 0 rows affected = already a member (idempotent add); the store then reads the STORED row
// back with GetGroupMember so the response carries the original added_by/added_at.
func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, addGroupMember, arg.GroupID, arg.MemberID, arg.AddedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countGroups = `-- name: CountGroups :one
SELECT count(*) FROM org.group WHERE company_id = $1
`

func (q *Queries) CountGroups(ctx context.Context, companyID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGroups, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMemberDirectory = `-- name: CountMemberDirectory :one
SELECT count(*)
FROM org.member m
WHERE m.company_id = $1 AND m.is_active = true
  AND ($2::text IS NULL
       OR m.display_name ILIKE '%' || $2::text || '%' ESCAPE '\'
       OR m.email ILIKE '%' || $2::text || '%' ESCAPE '\')
`

type CountMemberDirectoryParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	Q         *string     `json:"q"`
}

func (q *Queries) CountMemberDirectory(ctx context.Context, arg CountMemberDirectoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMemberDirectory, arg.CompanyID, arg.Q)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMembers = `-- name: CountMembers :one
SELECT count(*) FROM org.member WHERE company_id = $1
`

func (q *Queries) CountMembers(ctx context.Context, companyID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMembers, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMembersForCompany = `-- name: CountMembersForCompany :one
SELECT count(*) FROM org.member WHERE company_id = $1
`

func (q *Queries) CountMembersForCompany(ctx context.Context, companyID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMembersForCompany, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrgUnitChildren = `-- name: CountOrgUnitChildren :one
SELECT count(*) FROM org.org_unit WHERE parent_id = $1
`

func (q *Queries) CountOrgUnitChildren(ctx context.Context, parentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrgUnitChildren, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOtherOpenAssignments = `-- name: CountOtherOpenAssignments :one
SELECT count(*) FROM org.position_assignment
WHERE position_id = $2 AND member_id = $3 AND valid_to IS NULL AND id <> $1
`

type CountOtherOpenAssignmentsParams struct {
	ID         pgtype.UUID `json:"id"`
	PositionID pgtype.UUID `json:"position_id"`
	MemberID   pgtype.UUID `json:"member_id"`
}

// Open (valid_to IS NULL) assignments for the same (position, member) pair other than $1 — the
// holder tuple is revoked only when this count is zero (ending one of several open windows must
// not revoke the access another still-open window confers).
func (q *Queries) CountOtherOpenAssignments(ctx context.Context, arg CountOtherOpenAssignmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOtherOpenAssignments, arg.ID, arg.PositionID, arg.MemberID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPositions = `-- name: CountPositions :one
SELECT count(*) FROM org.position WHERE company_id = $1
`

func (q *Queries) CountPositions(ctx context.Context, companyID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPositions, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAssignment = `-- name: CreateAssignment :one
INSERT INTO org.position_assignment (position_id, member_id, valid_from, valid_to)
VALUES ($1, $2, $3, $4)
RETURNING id, position_id, member_id, valid_from, valid_to
`

type CreateAssignmentParams struct {
	PositionID pgtype.UUID `json:"position_id"`
	MemberID   pgtype.UUID `json:"member_id"`
	ValidFrom  pgtype.Date `json:"valid_from"`
	ValidTo    pgtype.Date `json:"valid_to"`
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (OrgPositionAssignment, error) {
	row := q.db.QueryRow(ctx, createAssignment,
		arg.PositionID,
		arg.MemberID,
		arg.ValidFrom,
		arg.ValidTo,
	)
	var i OrgPositionAssignment
	err := row.Scan(
		&i.ID,
		&i.PositionID,
		&i.MemberID,
		&i.ValidFrom,
		&i.ValidTo,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO org.group (company_id, code, name, source, external_ref)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, company_id, code, name, source, external_ref, is_active, created_at, updated_at
`

type CreateGroupParams struct {
	CompanyID   pgtype.UUID `json:"company_id"`
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Source      string      `json:"source"`
	ExternalRef *string     `json:"external_ref"`
}

// source defaults to 'kiban' at the DB level; only an external sync writer would pass another
// source value explicitly, the org admin API never does.
func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (OrgGroup, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.CompanyID,
		arg.Code,
		arg.Name,
		arg.Source,
		arg.ExternalRef,
	)
	var i OrgGroup
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.Source,
		&i.ExternalRef,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMember = `-- name: CreateMember :one
INSERT INTO org.member (company_id, code, display_name, email, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, company_id, code, display_name, email, user_id, is_active
`

type CreateMemberParams struct {
	CompanyID   pgtype.UUID `json:"company_id"`
	Code        string      `json:"code"`
	DisplayName string      `json:"display_name"`
	Email       *string     `json:"email"`
	IsActive    bool        `json:"is_active"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (OrgMember, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.CompanyID,
		arg.Code,
		arg.DisplayName,
		arg.Email,
		arg.IsActive,
	)
	var i OrgMember
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.DisplayName,
		&i.Email,
		&i.UserID,
		&i.IsActive,
	)
	return i, err
}

const createOrgUnit = `-- name: CreateOrgUnit :one
INSERT INTO org.org_unit (type_key, parent_id, code, name, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, type_key, parent_id, code, name, is_active
`

type CreateOrgUnitParams struct {
	TypeKey  string      `json:"type_key"`
	ParentID pgtype.UUID `json:"parent_id"`
	Code     string      `json:"code"`
	Name     string      `json:"name"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) CreateOrgUnit(ctx context.Context, arg CreateOrgUnitParams) (OrgOrgUnit, error) {
	row := q.db.QueryRow(ctx, createOrgUnit,
		arg.TypeKey,
		arg.ParentID,
		arg.Code,
		arg.Name,
		arg.IsActive,
	)
	var i OrgOrgUnit
	err := row.Scan(
		&i.ID,
		&i.TypeKey,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.IsActive,
	)
	return i, err
}

const createPosition = `-- name: CreatePosition :one
INSERT INTO org.position (company_id, code, title, org_unit_id)
VALUES ($1, $2, $3, $4)
RETURNING id, company_id, code, title, org_unit_id
`

type CreatePositionParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	Code      string      `json:"code"`
	Title     string      `json:"title"`
	OrgUnitID pgtype.UUID `json:"org_unit_id"`
}

func (q *Queries) CreatePosition(ctx context.Context, arg CreatePositionParams) (OrgPosition, error) {
	row := q.db.QueryRow(ctx, createPosition,
		arg.CompanyID,
		arg.Code,
		arg.Title,
		arg.OrgUnitID,
	)
	var i OrgPosition
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Title,
		&i.OrgUnitID,
	)
	return i, err
}

const deleteOrgUnit = `-- name: DeleteOrgUnit :execrows
DELETE FROM org.org_unit WHERE id = $1
`

func (q *Queries) DeleteOrgUnit(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrgUnit, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePosition = `-- name: DeletePosition :execrows
DELETE FROM org.position WHERE id = $1
`

func (q *Queries) DeletePosition(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePosition, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const endAssignment = `-- name: EndAssignment :one
UPDATE org.position_assignment SET valid_to = $2 WHERE id = $1 RETURNING id, position_id, member_id, valid_from, valid_to
`

type EndAssignmentParams struct {
	ID      pgtype.UUID `json:"id"`
	ValidTo pgtype.Date `json:"valid_to"`
}

func (q *Queries) EndAssignment(ctx context.Context, arg EndAssignmentParams) (OrgPositionAssignment, error) {
	row := q.db.QueryRow(ctx, endAssignment, arg.ID, arg.ValidTo)
	var i OrgPositionAssignment
	err := row.Scan(
		&i.ID,
		&i.PositionID,
		&i.MemberID,
		&i.ValidFrom,
		&i.ValidTo,
	)
	return i, err
}

const getAssignment = `-- name: GetAssignment :one
SELECT id, position_id, member_id, valid_from, valid_to FROM org.position_assignment WHERE id = $1
`

func (q *Queries) GetAssignment(ctx context.Context, id pgtype.UUID) (OrgPositionAssignment, error) {
	row := q.db.QueryRow(ctx, getAssignment, id)
	var i OrgPositionAssignment
	err := row.Scan(
		&i.ID,
		&i.PositionID,
		&i.MemberID,
		&i.ValidFrom,
		&i.ValidTo,
	)
	return i, err
}

const getAssignmentOnDate = `-- name: GetAssignmentOnDate :one
SELECT id, position_id, member_id, valid_from, valid_to FROM org.position_assignment
WHERE position_id = $1 AND valid_from <= $2 AND (valid_to IS NULL OR valid_to > $2)
LIMIT 1
`

type GetAssignmentOnDateParams struct {
	PositionID pgtype.UUID `json:"position_id"`
	ValidFrom  pgtype.Date `json:"valid_from"`
}

// "who holds position P on date D". valid_to is HALF-OPEN/EXCLUSIVE
// (migrations/org/0009) — D is held when valid_from <= D < valid_to (or valid_to IS NULL), never
// valid_to >= D (which would have D's holder-of-record still be the PREVIOUS occupant on the
// exact day a same-day handover's successor starts).
func (q *Queries) GetAssignmentOnDate(ctx context.Context, arg GetAssignmentOnDateParams) (OrgPositionAssignment, error) {
	row := q.db.QueryRow(ctx, getAssignmentOnDate, arg.PositionID, arg.ValidFrom)
	var i OrgPositionAssignment
	err := row.Scan(
		&i.ID,
		&i.PositionID,
		&i.MemberID,
		&i.ValidFrom,
		&i.ValidTo,
	)
	return i, err
}

const getCompanyState = `-- name: GetCompanyState :one
SELECT ou.id, ou.is_active
FROM org.org_unit ou
JOIN org.org_unit_type ut ON ut.key = ou.type_key
WHERE ou.id = $1 AND ut.is_company = true
`

type GetCompanyStateRow struct {
	ID       pgtype.UUID `json:"id"`
	IsActive bool        `json:"is_active"`
}

// Company-state fact for authz's decision.CompanySource. A row is only returned when id
// resolves to a COMPANY-typed org_unit (org_unit_type.is_company = true) — a non-company unit or
// an unknown id both come back as no-rows, which the store maps to exists=false (never a
// fabricated company for an org_unit of the wrong type).
func (q *Queries) GetCompanyState(ctx context.Context, id pgtype.UUID) (GetCompanyStateRow, error) {
	row := q.db.QueryRow(ctx, getCompanyState, id)
	var i GetCompanyStateRow
	err := row.Scan(&i.ID, &i.IsActive)
	return i, err
}

const getGroup = `-- name: GetGroup :one
SELECT id, company_id, code, name, source, external_ref, is_active, created_at, updated_at FROM org.group WHERE id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id pgtype.UUID) (OrgGroup, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i OrgGroup
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.Source,
		&i.ExternalRef,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupMember = `-- name: GetGroupMember :one
SELECT group_id, member_id, added_by, added_at FROM org.group_member WHERE group_id = $1 AND member_id = $2
`

type GetGroupMemberParams struct {
	GroupID  pgtype.UUID `json:"group_id"`
	MemberID pgtype.UUID `json:"member_id"`
}

func (q *Queries) GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (OrgGroupMember, error) {
	row := q.db.QueryRow(ctx, getGroupMember, arg.GroupID, arg.MemberID)
	var i OrgGroupMember
	err := row.Scan(
		&i.GroupID,
		&i.MemberID,
		&i.AddedBy,
		&i.AddedAt,
	)
	return i, err
}

const getIdentityUserByKcSub = `-- name: GetIdentityUserByKcSub :one
SELECT id, kc_sub, email, preferred_username, lifecycle FROM identity.user_read_v WHERE kc_sub = $1
`

// The published read contract — the ONLY way org reads identity data. Resolves the
// internal user_id to store in member.user_id after the HTTP-level liveness check
// (internal/org/identityclient.go) has confirmed the account exists.
func (q *Queries) GetIdentityUserByKcSub(ctx context.Context, kcSub string) (IdentityUserReadV, error) {
	row := q.db.QueryRow(ctx, getIdentityUserByKcSub, kcSub)
	var i IdentityUserReadV
	err := row.Scan(
		&i.ID,
		&i.KcSub,
		&i.Email,
		&i.PreferredUsername,
		&i.Lifecycle,
	)
	return i, err
}

const getMember = `-- name: GetMember :one
SELECT id, company_id, code, display_name, email, user_id, is_active FROM org.member WHERE id = $1
`

func (q *Queries) GetMember(ctx context.Context, id pgtype.UUID) (OrgMember, error) {
	row := q.db.QueryRow(ctx, getMember, id)
	var i OrgMember
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.DisplayName,
		&i.Email,
		&i.UserID,
		&i.IsActive,
	)
	return i, err
}

const getMemberByCompanyAndKcSub = `-- name: GetMemberByCompanyAndKcSub :one
SELECT m.id, m.is_active
FROM org.member m
JOIN identity.user_read_v u ON u.id = m.user_id
WHERE m.company_id = $1 AND u.kc_sub = $2
`

type GetMemberByCompanyAndKcSubParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	KcSub     string      `json:"kc_sub"`
}

type GetMemberByCompanyAndKcSubRow struct {
	ID       pgtype.UUID `json:"id"`
	IsActive bool        `json:"is_active"`
}

// Membership fact for authz's decision.MembershipSource. Resolves the member linked to
// kcSub within companyId via the published identity.user_read_v join (same read path
// ListMembers/GetMemberWithUser already use) — never a per-row identity call.
func (q *Queries) GetMemberByCompanyAndKcSub(ctx context.Context, arg GetMemberByCompanyAndKcSubParams) (GetMemberByCompanyAndKcSubRow, error) {
	row := q.db.QueryRow(ctx, getMemberByCompanyAndKcSub, arg.CompanyID, arg.KcSub)
	var i GetMemberByCompanyAndKcSubRow
	err := row.Scan(&i.ID, &i.IsActive)
	return i, err
}

const getMemberWithUser = `-- name: GetMemberWithUser :one
SELECT m.id, m.company_id, m.code, m.display_name, m.email, m.user_id, m.is_active,
       u.kc_sub AS user_kc_sub, u.email AS user_email,
       u.preferred_username AS user_preferred_username, u.lifecycle AS user_lifecycle
FROM org.member m
LEFT JOIN identity.user_read_v u ON u.id = m.user_id
WHERE m.id = $1
`

type GetMemberWithUserRow struct {
	ID                    pgtype.UUID `json:"id"`
	CompanyID             pgtype.UUID `json:"company_id"`
	Code                  string      `json:"code"`
	DisplayName           string      `json:"display_name"`
	Email                 *string     `json:"email"`
	UserID                pgtype.UUID `json:"user_id"`
	IsActive              bool        `json:"is_active"`
	UserKcSub             *string     `json:"user_kc_sub"`
	UserEmail             *string     `json:"user_email"`
	UserPreferredUsername *string     `json:"user_preferred_username"`
	UserLifecycle         *string     `json:"user_lifecycle"`
}

func (q *Queries) GetMemberWithUser(ctx context.Context, id pgtype.UUID) (GetMemberWithUserRow, error) {
	row := q.db.QueryRow(ctx, getMemberWithUser, id)
	var i GetMemberWithUserRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.DisplayName,
		&i.Email,
		&i.UserID,
		&i.IsActive,
		&i.UserKcSub,
		&i.UserEmail,
		&i.UserPreferredUsername,
		&i.UserLifecycle,
	)
	return i, err
}

const getOrgUnit = `-- name: GetOrgUnit :one
SELECT id, type_key, parent_id, code, name, is_active FROM org.org_unit WHERE id = $1
`

func (q *Queries) GetOrgUnit(ctx context.Context, id pgtype.UUID) (OrgOrgUnit, error) {
	row := q.db.QueryRow(ctx, getOrgUnit, id)
	var i OrgOrgUnit
	err := row.Scan(
		&i.ID,
		&i.TypeKey,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.IsActive,
	)
	return i, err
}

const getOrgUnitType = `-- name: GetOrgUnitType :one

SELECT key, label, is_company FROM org.org_unit_type WHERE key = $1
`

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) GetOrgUnitType(ctx context.Context, key string) (OrgOrgUnitType, error) {
	row := q.db.QueryRow(ctx, getOrgUnitType, key)
	var i OrgOrgUnitType
	err := row.Scan(&i.Key, &i.Label, &i.IsCompany)
	return i, err
}

const getPosition = `-- name: GetPosition :one
SELECT id, company_id, code, title, org_unit_id FROM org.position WHERE id = $1
`

func (q *Queries) GetPosition(ctx context.Context, id pgtype.UUID) (OrgPosition, error) {
	row := q.db.QueryRow(ctx, getPosition, id)
	var i OrgPosition
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Title,
		&i.OrgUnitID,
	)
	return i, err
}

const linkMemberUser = `-- name: LinkMemberUser :one
UPDATE org.member SET user_id = $2 WHERE id = $1 RETURNING id, company_id, code, display_name, email, user_id, is_active
`

type LinkMemberUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) LinkMemberUser(ctx context.Context, arg LinkMemberUserParams) (OrgMember, error) {
	row := q.db.QueryRow(ctx, linkMemberUser, arg.ID, arg.UserID)
	var i OrgMember
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.DisplayName,
		&i.Email,
		&i.UserID,
		&i.IsActive,
	)
	return i, err
}

const listActiveCompaniesForKcSub = `-- name: ListActiveCompaniesForKcSub :many
SELECT ou.id, ou.code, ou.name, ou.is_active
FROM org.member m
JOIN identity.user_read_v u ON u.id = m.user_id
JOIN org.org_unit ou ON ou.id = m.company_id
WHERE u.kc_sub = $1 AND m.is_active = true AND ou.is_active = true
ORDER BY ou.code
`

type ListActiveCompaniesForKcSubRow struct {
	ID       pgtype.UUID `json:"id"`
	Code     string      `json:"code"`
	Name     string      `json:"name"`
	IsActive bool        `json:"is_active"`
}

// The company-switcher source — companies where kcSub has an ACTIVE membership in an ACTIVE
// company. One SQL query (member JOIN identity.user_read_v JOIN org_unit), filtered/sorted in
// SQL — never in-memory. Self-scoped by construction: kcSub is the caller's own identity, a
// param at the internal layer; the gateway injects the bearer's own kcSub, never trusting a
// client-supplied value.
// Both m.is_active (the membership) and ou.is_active (the company itself) are required — an
// inactive company is never offered as a switch target even if the membership row is still
// active.
func (q *Queries) ListActiveCompaniesForKcSub(ctx context.Context, kcSub string) ([]ListActiveCompaniesForKcSubRow, error) {
	rows, err := q.db.Query(ctx, listActiveCompaniesForKcSub, kcSub)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveCompaniesForKcSubRow
	for rows.Next() {
		var i ListActiveCompaniesForKcSubRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT gm.group_id, gm.member_id, gm.added_by, gm.added_at,
       m.display_name AS member_display_name, m.email AS member_email
FROM org.group_member gm
JOIN org.member m ON m.id = gm.member_id
WHERE gm.group_id = $1
ORDER BY m.display_name
`

type ListGroupMembersRow struct {
	GroupID           pgtype.UUID        `json:"group_id"`
	MemberID          pgtype.UUID        `json:"member_id"`
	AddedBy           string             `json:"added_by"`
	AddedAt           pgtype.Timestamptz `json:"added_at"`
	MemberDisplayName string             `json:"member_display_name"`
	MemberEmail       *string            `json:"member_email"`
}

// Group membership read: member rows for a group, joined for display fields — the shape the
// admin surface and the assignable-groups module read both need.
func (q *Queries) ListGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]ListGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupMembersRow
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(
			&i.GroupID,
			&i.MemberID,
			&i.AddedBy,
			&i.AddedAt,
			&i.MemberDisplayName,
			&i.MemberEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsWithMemberCount = `-- name: ListGroupsWithMemberCount :many
SELECT g.id, g.company_id, g.code, g.name, g.source, g.external_ref, g.is_active, g.created_at, g.updated_at,
       count(gm.member_id) AS member_count
FROM org.group g
LEFT JOIN org.group_member gm ON gm.group_id = g.id
WHERE g.company_id = $1
GROUP BY g.id
ORDER BY g.code
LIMIT $2 OFFSET $3
`

type ListGroupsWithMemberCountParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListGroupsWithMemberCountRow struct {
	ID          pgtype.UUID        `json:"id"`
	CompanyID   pgtype.UUID        `json:"company_id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Source      string             `json:"source"`
	ExternalRef *string            `json:"external_ref"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	MemberCount int64              `json:"member_count"`
}

// The admin list surface: each row carries its member
// count so the UI can render "N members" without a second round trip per row.
func (q *Queries) ListGroupsWithMemberCount(ctx context.Context, arg ListGroupsWithMemberCountParams) ([]ListGroupsWithMemberCountRow, error) {
	rows, err := q.db.Query(ctx, listGroupsWithMemberCount, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupsWithMemberCountRow
	for rows.Next() {
		var i ListGroupsWithMemberCountRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Code,
			&i.Name,
			&i.Source,
			&i.ExternalRef,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberDirectory = `-- name: ListMemberDirectory :many
SELECT m.id, m.display_name, m.email, (m.user_id IS NOT NULL)::boolean AS has_linked_user
FROM org.member m
WHERE m.company_id = $1 AND m.is_active = true
  AND ($4::text IS NULL
       OR m.display_name ILIKE '%' || $4::text || '%' ESCAPE '\'
       OR m.email ILIKE '%' || $4::text || '%' ESCAPE '\')
ORDER BY m.display_name
LIMIT $2 OFFSET $3
`

type ListMemberDirectoryParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
	Q         *string     `json:"q"`
}

type ListMemberDirectoryRow struct {
	ID            pgtype.UUID `json:"id"`
	DisplayName   string      `json:"display_name"`
	Email         *string     `json:"email"`
	HasLinkedUser bool        `json:"has_linked_user"`
}

// The browser-reachable member directory (share-with/assign-to picker). REDUCED view
// (id/displayName/email/hasLinkedUser only — least disclosure) over ACTIVE members of one
// company, optional case-insensitive LITERAL substring filter on displayName/email (sqlc.narg —
// NULL means "no filter"; the store escapes `\`, `%`, `_` in q, hence ESCAPE '\'),
// filtered/sorted/paginated entirely in SQL.
func (q *Queries) ListMemberDirectory(ctx context.Context, arg ListMemberDirectoryParams) ([]ListMemberDirectoryRow, error) {
	rows, err := q.db.Query(ctx, listMemberDirectory,
		arg.CompanyID,
		arg.Limit,
		arg.Offset,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMemberDirectoryRow
	for rows.Next() {
		var i ListMemberDirectoryRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Email,
			&i.HasLinkedUser,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT m.id, m.company_id, m.code, m.display_name, m.email, m.user_id, m.is_active,
       u.kc_sub AS user_kc_sub, u.email AS user_email,
       u.preferred_username AS user_preferred_username, u.lifecycle AS user_lifecycle
FROM org.member m
LEFT JOIN identity.user_read_v u ON u.id = m.user_id
WHERE m.company_id = $1
ORDER BY m.code
LIMIT $2 OFFSET $3
`

type ListMembersParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListMembersRow struct {
	ID                    pgtype.UUID `json:"id"`
	CompanyID             pgtype.UUID `json:"company_id"`
	Code                  string      `json:"code"`
	DisplayName           string      `json:"display_name"`
	Email                 *string     `json:"email"`
	UserID                pgtype.UUID `json:"user_id"`
	IsActive              bool        `json:"is_active"`
	UserKcSub             *string     `json:"user_kc_sub"`
	UserEmail             *string     `json:"user_email"`
	UserPreferredUsername *string     `json:"user_preferred_username"`
	UserLifecycle         *string     `json:"user_lifecycle"`
}

// Member directory read: one SQL query, JOIN identity.user_read_v for linked-user display
// fields, paginated/authorized in SQL — never per-row API calls.
func (q *Queries) ListMembers(ctx context.Context, arg ListMembersParams) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Code,
			&i.DisplayName,
			&i.Email,
			&i.UserID,
			&i.IsActive,
			&i.UserKcSub,
			&i.UserEmail,
			&i.UserPreferredUsername,
			&i.UserLifecycle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositions = `-- name: ListPositions :many
SELECT id, company_id, code, title, org_unit_id FROM org.position WHERE company_id = $1 ORDER BY code LIMIT $2 OFFSET $3
`

type ListPositionsParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListPositions(ctx context.Context, arg ListPositionsParams) ([]OrgPosition, error) {
	rows, err := q.db.Query(ctx, listPositions, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgPosition
	for rows.Next() {
		var i OrgPosition
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Code,
			&i.Title,
			&i.OrgUnitID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositionsWithHolder = `-- name: ListPositionsWithHolder :many
SELECT p.id, p.company_id, p.code, p.title, p.org_unit_id,
       a.id AS assignment_id, a.member_id AS assignment_member_id,
       mem.display_name AS holder_display_name
FROM org.position p
LEFT JOIN org.position_assignment a
       ON a.position_id = p.id
      AND a.valid_from <= $4::date
      AND (a.valid_to IS NULL OR a.valid_to > $4::date)
LEFT JOIN org.member mem ON mem.id = a.member_id
WHERE p.company_id = $1
ORDER BY p.code
LIMIT $2 OFFSET $3
`

type ListPositionsWithHolderParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
	Today     pgtype.Date `json:"today"`
}

type ListPositionsWithHolderRow struct {
	ID                 pgtype.UUID `json:"id"`
	CompanyID          pgtype.UUID `json:"company_id"`
	Code               string      `json:"code"`
	Title              string      `json:"title"`
	OrgUnitID          pgtype.UUID `json:"org_unit_id"`
	AssignmentID       pgtype.UUID `json:"assignment_id"`
	AssignmentMemberID pgtype.UUID `json:"assignment_member_id"`
	HolderDisplayName  *string     `json:"holder_display_name"`
}

// The admin list surface — each row carries the CURRENT assignment (assignmentId/memberId/
// holder displayName), the fields the UI needs to END a tenure. "current" = today's half-open
// window (migrations/org/0009): valid_from <= today AND
// (valid_to IS NULL OR valid_to > today). today is the store's tenant-timezone date (the same
// clock assign-NOW/end-NOW stamp), never CURRENT_DATE (the DB session's zone — a second clock).
// LEFT JOINs so an unassigned position still returns a row with NULL assignment fields, never
// omitted.
func (q *Queries) ListPositionsWithHolder(ctx context.Context, arg ListPositionsWithHolderParams) ([]ListPositionsWithHolderRow, error) {
	rows, err := q.db.Query(ctx, listPositionsWithHolder,
		arg.CompanyID,
		arg.Limit,
		arg.Offset,
		arg.Today,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPositionsWithHolderRow
	for rows.Next() {
		var i ListPositionsWithHolderRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Code,
			&i.Title,
			&i.OrgUnitID,
			&i.AssignmentID,
			&i.AssignmentMemberID,
			&i.HolderDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupMember = `-- name: RemoveGroupMember :execrows
DELETE FROM org.group_member WHERE group_id = $1 AND member_id = $2
`

type RemoveGroupMemberParams struct {
	GroupID  pgtype.UUID `json:"group_id"`
	MemberID pgtype.UUID `json:"member_id"`
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeGroupMember, arg.GroupID, arg.MemberID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const subtreeOrgUnits = `-- name: SubtreeOrgUnits :many
WITH RECURSIVE subtree AS (
    SELECT r.id, r.type_key, r.parent_id, r.code, r.name, r.is_active, 0 AS depth
    FROM org.org_unit r
    WHERE r.id = $1
    UNION ALL
    SELECT u.id, u.type_key, u.parent_id, u.code, u.name, u.is_active, s.depth + 1
    FROM org.org_unit u
    JOIN subtree s ON u.parent_id = s.id
    WHERE s.depth < 32
)
SELECT subtree.id, subtree.type_key, subtree.parent_id, subtree.code, subtree.name, subtree.is_active, subtree.depth
FROM subtree ORDER BY depth, code
`

type SubtreeOrgUnitsRow struct {
	ID       pgtype.UUID `json:"id"`
	TypeKey  string      `json:"type_key"`
	ParentID pgtype.UUID `json:"parent_id"`
	Code     string      `json:"code"`
	Name     string      `json:"name"`
	IsActive bool        `json:"is_active"`
	Depth    int32       `json:"depth"`
}

// Recursive CTE, depth-bounded 32. Powers GET /internal/org/units/{id}/subtree and the
// cycle-proof parent-change validation (a candidate new parent must not already be in the
// moved unit's own subtree).
func (q *Queries) SubtreeOrgUnits(ctx context.Context, id pgtype.UUID) ([]SubtreeOrgUnitsRow, error) {
	rows, err := q.db.Query(ctx, subtreeOrgUnits, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubtreeOrgUnitsRow
	for rows.Next() {
		var i SubtreeOrgUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.TypeKey,
			&i.ParentID,
			&i.Code,
			&i.Name,
			&i.IsActive,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkMemberUser = `-- name: UnlinkMemberUser :one
UPDATE org.member SET user_id = NULL WHERE id = $1 RETURNING id, company_id, code, display_name, email, user_id, is_active
`

func (q *Queries) UnlinkMemberUser(ctx context.Context, id pgtype.UUID) (OrgMember, error) {
	row := q.db.QueryRow(ctx, unlinkMemberUser, id)
	var i OrgMember
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.DisplayName,
		&i.Email,
		&i.UserID,
		&i.IsActive,
	)
	return i, err
}

const updateMember = `-- name: UpdateMember :one
UPDATE org.member
SET display_name = $2, email = $3, is_active = $4
WHERE id = $1
RETURNING id, company_id, code, display_name, email, user_id, is_active
`

type UpdateMemberParams struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName string      `json:"display_name"`
	Email       *string     `json:"email"`
	IsActive    bool        `json:"is_active"`
}

func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (OrgMember, error) {
	row := q.db.QueryRow(ctx, updateMember,
		arg.ID,
		arg.DisplayName,
		arg.Email,
		arg.IsActive,
	)
	var i OrgMember
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.DisplayName,
		&i.Email,
		&i.UserID,
		&i.IsActive,
	)
	return i, err
}

const updateOrgUnit = `-- name: UpdateOrgUnit :one
UPDATE org.org_unit
SET parent_id = $2, code = $3, name = $4, is_active = $5
WHERE id = $1
RETURNING id, type_key, parent_id, code, name, is_active
`

type UpdateOrgUnitParams struct {
	ID       pgtype.UUID `json:"id"`
	ParentID pgtype.UUID `json:"parent_id"`
	Code     string      `json:"code"`
	Name     string      `json:"name"`
	IsActive bool        `json:"is_active"`
}

// type_key is deliberately absent: org-unit type is immutable after creation.
func (q *Queries) UpdateOrgUnit(ctx context.Context, arg UpdateOrgUnitParams) (OrgOrgUnit, error) {
	row := q.db.QueryRow(ctx, updateOrgUnit,
		arg.ID,
		arg.ParentID,
		arg.Code,
		arg.Name,
		arg.IsActive,
	)
	var i OrgOrgUnit
	err := row.Scan(
		&i.ID,
		&i.TypeKey,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.IsActive,
	)
	return i, err
}

const updatePosition = `-- name: UpdatePosition :one
UPDATE org.position SET title = $2, org_unit_id = $3 WHERE id = $1 RETURNING id, company_id, code, title, org_unit_id
`

type UpdatePositionParams struct {
	ID        pgtype.UUID `json:"id"`
	Title     string      `json:"title"`
	OrgUnitID pgtype.UUID `json:"org_unit_id"`
}

func (q *Queries) UpdatePosition(ctx context.Context, arg UpdatePositionParams) (OrgPosition, error) {
	row := q.db.QueryRow(ctx, updatePosition, arg.ID, arg.Title, arg.OrgUnitID)
	var i OrgPosition
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Title,
		&i.OrgUnitID,
	)
	return i, err
}
