// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package registry

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditRegistryEvent struct {
	ID            int64              `json:"id"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	Actor         string             `json:"actor"`
	Action        string             `json:"action"`
	Subject       string             `json:"subject"`
	Payload       []byte             `json:"payload"`
	CorrelationID *string            `json:"correlation_id"`
}

type PlatformModuleCatalog struct {
	ModuleKey       string `json:"module_key"`
	DisplayName     string `json:"display_name"`
	ScopeType       string `json:"scope_type"`
	Mandatory       bool   `json:"mandatory"`
	BasePath        string `json:"base_path"`
	HealthPath      string `json:"health_path"`
	Port            int32  `json:"port"`
	LicenseClass    string `json:"license_class"`
	ManifestVersion string `json:"manifest_version"`
	IsActive        bool   `json:"is_active"`
}

type PlatformModuleDependency struct {
	ModuleKey          string `json:"module_key"`
	DependsOnModuleKey string `json:"depends_on_module_key"`
	VersionRange       string `json:"version_range"`
}

type PlatformModuleInstallation struct {
	ModuleKey    string             `json:"module_key"`
	Installed    bool               `json:"installed"`
	Enabled      bool               `json:"enabled"`
	Version      *string            `json:"version"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
	LastSeenAt   pgtype.Timestamptz `json:"last_seen_at"`
}

type PlatformTenantDefault struct {
	TenantID string `json:"tenant_id"`
	Locale   string `json:"locale"`
	Timezone string `json:"timezone"`
	Currency string `json:"currency"`
}
