// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package registry

import (
	"context"
)

const getModuleCatalogEntry = `-- name: GetModuleCatalogEntry :one
SELECT module_key, display_name, scope_type, mandatory, base_path, health_path, port, license_class, manifest_version, is_active FROM platform.module_catalog WHERE module_key = $1
`

func (q *Queries) GetModuleCatalogEntry(ctx context.Context, moduleKey string) (PlatformModuleCatalog, error) {
	row := q.db.QueryRow(ctx, getModuleCatalogEntry, moduleKey)
	var i PlatformModuleCatalog
	err := row.Scan(
		&i.ModuleKey,
		&i.DisplayName,
		&i.ScopeType,
		&i.Mandatory,
		&i.BasePath,
		&i.HealthPath,
		&i.Port,
		&i.LicenseClass,
		&i.ManifestVersion,
		&i.IsActive,
	)
	return i, err
}

const listInstallationStatusForKeys = `-- name: ListInstallationStatusForKeys :many
SELECT module_key, installed, enabled
FROM platform.module_installation
WHERE module_key = ANY($1::text[])
`

type ListInstallationStatusForKeysRow struct {
	ModuleKey string `json:"module_key"`
	Installed bool   `json:"installed"`
	Enabled   bool   `json:"enabled"`
}

// Installation status for a module and its transitive dependency keys (order-preserving isn't
// required; the caller indexes by module_key). Modules with no installation row yet are simply
// absent from the result (never installed/enabled).
func (q *Queries) ListInstallationStatusForKeys(ctx context.Context, moduleKeys []string) ([]ListInstallationStatusForKeysRow, error) {
	rows, err := q.db.Query(ctx, listInstallationStatusForKeys, moduleKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInstallationStatusForKeysRow
	for rows.Next() {
		var i ListInstallationStatusForKeysRow
		if err := rows.Scan(&i.ModuleKey, &i.Installed, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModuleCatalog = `-- name: ListModuleCatalog :many
SELECT c.module_key, c.display_name, c.scope_type, c.mandatory, c.base_path, c.health_path, c.port, c.license_class, c.manifest_version, c.is_active, COALESCE(i.installed, false) AS installed, COALESCE(i.enabled, false) AS enabled
FROM platform.module_catalog c
LEFT JOIN platform.module_installation i ON i.module_key = c.module_key
ORDER BY c.module_key
`

type ListModuleCatalogRow struct {
	ModuleKey       string `json:"module_key"`
	DisplayName     string `json:"display_name"`
	ScopeType       string `json:"scope_type"`
	Mandatory       bool   `json:"mandatory"`
	BasePath        string `json:"base_path"`
	HealthPath      string `json:"health_path"`
	Port            int32  `json:"port"`
	LicenseClass    string `json:"license_class"`
	ManifestVersion string `json:"manifest_version"`
	IsActive        bool   `json:"is_active"`
	Installed       bool   `json:"installed"`
	Enabled         bool   `json:"enabled"`
}

func (q *Queries) ListModuleCatalog(ctx context.Context) ([]ListModuleCatalogRow, error) {
	rows, err := q.db.Query(ctx, listModuleCatalog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModuleCatalogRow
	for rows.Next() {
		var i ListModuleCatalogRow
		if err := rows.Scan(
			&i.ModuleKey,
			&i.DisplayName,
			&i.ScopeType,
			&i.Mandatory,
			&i.BasePath,
			&i.HealthPath,
			&i.Port,
			&i.LicenseClass,
			&i.ManifestVersion,
			&i.IsActive,
			&i.Installed,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransitiveDependencyKeys = `-- name: ListTransitiveDependencyKeys :many
WITH RECURSIVE deps AS (
    SELECT md0.depends_on_module_key AS dep_key, ARRAY[md0.module_key, md0.depends_on_module_key] AS path
    FROM platform.module_dependency md0
    WHERE md0.module_key = $1
    UNION
    SELECT md.depends_on_module_key, d.path || md.depends_on_module_key
    FROM platform.module_dependency md
    JOIN deps d ON md.module_key = d.dep_key
    WHERE NOT md.depends_on_module_key = ANY(d.path)
)
SELECT DISTINCT dep_key FROM deps
`

// Transitive dependency-key closure of one module, cycle-safe: the `path` array tracks the
// walk so far and a step is only taken if it doesn't revisit a key already on the path
// (module_dependency.CHECK forbids self-deps, so path always starts with at least one edge).
func (q *Queries) ListTransitiveDependencyKeys(ctx context.Context, moduleKey string) ([]string, error) {
	rows, err := q.db.Query(ctx, listTransitiveDependencyKeys, moduleKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var dep_key string
		if err := rows.Scan(&dep_key); err != nil {
			return nil, err
		}
		items = append(items, dep_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedModuleInstallationMissing = `-- name: SeedModuleInstallationMissing :execrows
INSERT INTO platform.module_installation (module_key, installed, enabled, version)
VALUES ($1, $2, $3, $4)
ON CONFLICT (module_key) DO NOTHING
`

type SeedModuleInstallationMissingParams struct {
	ModuleKey string  `json:"module_key"`
	Installed bool    `json:"installed"`
	Enabled   bool    `json:"enabled"`
	Version   *string `json:"version"`
}

// Insert only when absent; NEVER overwrites existing installed/enabled.
// ON CONFLICT DO NOTHING makes concurrent seeds (multi-replica boot) race-free.
func (q *Queries) SeedModuleInstallationMissing(ctx context.Context, arg SeedModuleInstallationMissingParams) (int64, error) {
	result, err := q.db.Exec(ctx, seedModuleInstallationMissing,
		arg.ModuleKey,
		arg.Installed,
		arg.Enabled,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setModuleEnabled = `-- name: SetModuleEnabled :one
UPDATE platform.module_installation
SET enabled = $2, last_seen_at = now()
WHERE module_key = $1
RETURNING module_key, installed, enabled, version, registered_at, last_seen_at
`

type SetModuleEnabledParams struct {
	ModuleKey string `json:"module_key"`
	Enabled   bool   `json:"enabled"`
}

func (q *Queries) SetModuleEnabled(ctx context.Context, arg SetModuleEnabledParams) (PlatformModuleInstallation, error) {
	row := q.db.QueryRow(ctx, setModuleEnabled, arg.ModuleKey, arg.Enabled)
	var i PlatformModuleInstallation
	err := row.Scan(
		&i.ModuleKey,
		&i.Installed,
		&i.Enabled,
		&i.Version,
		&i.RegisteredAt,
		&i.LastSeenAt,
	)
	return i, err
}

const upsertModuleCatalog = `-- name: UpsertModuleCatalog :exec


INSERT INTO platform.module_catalog (
    module_key, display_name, scope_type, mandatory, base_path, health_path, port,
    license_class, manifest_version, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (module_key) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    scope_type = EXCLUDED.scope_type,
    mandatory = EXCLUDED.mandatory,
    base_path = EXCLUDED.base_path,
    health_path = EXCLUDED.health_path,
    port = EXCLUDED.port,
    license_class = EXCLUDED.license_class,
    manifest_version = EXCLUDED.manifest_version,
    is_active = EXCLUDED.is_active
`

type UpsertModuleCatalogParams struct {
	ModuleKey       string `json:"module_key"`
	DisplayName     string `json:"display_name"`
	ScopeType       string `json:"scope_type"`
	Mandatory       bool   `json:"mandatory"`
	BasePath        string `json:"base_path"`
	HealthPath      string `json:"health_path"`
	Port            int32  `json:"port"`
	LicenseClass    string `json:"license_class"`
	ManifestVersion string `json:"manifest_version"`
	IsActive        bool   `json:"is_active"`
}

// SPDX-License-Identifier: Apache-2.0
// sqlc-generated queries for the registry service. Hand SQL for the recursive
// dependency walk; everything else is plain CRUD sqlc handles well.
// Manifest-owned fields sync on every boot (safe to overwrite — only operator state
// in module_installation is seed-missing-only).
func (q *Queries) UpsertModuleCatalog(ctx context.Context, arg UpsertModuleCatalogParams) error {
	_, err := q.db.Exec(ctx, upsertModuleCatalog,
		arg.ModuleKey,
		arg.DisplayName,
		arg.ScopeType,
		arg.Mandatory,
		arg.BasePath,
		arg.HealthPath,
		arg.Port,
		arg.LicenseClass,
		arg.ManifestVersion,
		arg.IsActive,
	)
	return err
}
