// SPDX-License-Identifier: Apache-2.0
package licensecheck

import (
	"os"
	"path/filepath"
	"testing"
)

func TestZone(t *testing.T) {
	cases := map[string]string{
		"web/sdk/src/index.ts":               Apache,
		"web/shell/src/main.tsx":             Apache,
		"modulekit/token.go":                 Apache,
		"modulekit/kittest/issuer.go":        Apache,
		"internal/modvalidate/manifest.go":   Apache,
		"internal/modvalidate/sub/x.go":      Apache,
		"cmd/modvalidate/main.go":            Apache,
		"internal/authz/harness/harness.go":  Apache,
		"docs/quickstart.md":                 Apache,
		"internal/authz/db.go":               Apache, // internal/ but NOT internal/modvalidate or internal/authz/harness
		"cmd/gateway/main.go":                Apache,
		"modules/docs/service/http.go":       Apache,
		"migrations/registry/0001_roles.sql": Apache,
		"infra/setup.sh":                     Apache,
		"contracts/wire-enums.json":          Apache,
		"tools/ratchetguard/ratchetguard.go": Apache,
		"scripts/coverage-gate.sh":           Apache,
		"vendor/x/y.go":                      "", // outside every zone
		"README.md":                          "", // outside every zone
	}
	for path, want := range cases {
		if got := Zone(path); got != want {
			t.Errorf("Zone(%q) = %q, want %q", path, got, want)
		}
	}
}

func TestExcluded(t *testing.T) {
	excluded := []string{
		"web/sdk/node_modules/x/y.ts",
		"web/node_modules/react/index.js",
		"web/sdk/dist/index.js",
		"coverage/report.html",
		"internal/registry/LICENSE",
		"docs/quickstart.md",            // not a checked extension
		"internal/registry/queries.sql", // wrong ext handled elsewhere; .sql is checked though — remove from excluded list
	}
	// The .md and .sql entries above illustrate two different reasons; re-split below.
	for _, p := range excluded[:6] {
		if !Excluded(p) {
			t.Errorf("Excluded(%q) = false, want true", p)
		}
	}
	if Excluded("internal/registry/queries.sql") {
		t.Errorf("Excluded(%q) = true, want false (.sql is a checked extension, not in an excluded dir)", "internal/registry/queries.sql")
	}

	included := []string{
		"internal/registry/queries.sql",
		"cmd/gateway/main.go",
		"web/sdk/src/index.ts",
		"infra/setup.sh",
	}
	for _, p := range included {
		if Excluded(p) {
			t.Errorf("Excluded(%q) = true, want false", p)
		}
	}
}

func TestHasHeader(t *testing.T) {
	data := []byte("// SPDX-License-Identifier: Apache-2.0\n\npackage foo\n")
	if !HasHeader(data, "// SPDX-License-Identifier: Apache-2.0") {
		t.Error("expected header to be found")
	}
	if HasHeader(data, "// SPDX-License-Identifier: MIT") {
		t.Error("expected mismatched header to not be found")
	}
	if HasHeader([]byte("package foo\n"), "// SPDX-License-Identifier: Apache-2.0") {
		t.Error("expected missing header to not be found")
	}
}

func TestIsGenerated(t *testing.T) {
	gen := []byte("// Code generated by sqlc. DO NOT EDIT.\npackage foo\n")
	if !isGenerated(gen) {
		t.Error("expected generated marker to be detected")
	}
	if isGenerated([]byte("package foo\n")) {
		t.Error("expected non-generated file to not be flagged")
	}
}

func TestInsertHeader_Go(t *testing.T) {
	out := InsertHeader([]byte("package foo\n\nfunc x() {}\n"), ".go", "// SPDX-License-Identifier: Apache-2.0")
	want := "// SPDX-License-Identifier: Apache-2.0\n\npackage foo\n\nfunc x() {}\n"
	if string(out) != want {
		t.Errorf("InsertHeader Go = %q, want %q", out, want)
	}
}

func TestInsertHeader_ShellPreservesShebang(t *testing.T) {
	out := InsertHeader([]byte("#!/usr/bin/env bash\necho hi\n"), ".sh", "# SPDX-License-Identifier: Apache-2.0")
	want := "#!/usr/bin/env bash\n# SPDX-License-Identifier: Apache-2.0\n\necho hi\n"
	if string(out) != want {
		t.Errorf("InsertHeader shell = %q, want %q", out, want)
	}
}

func TestInsertHeader_SQL(t *testing.T) {
	out := InsertHeader([]byte("CREATE TABLE t (id int);\n"), ".sql", "-- SPDX-License-Identifier: Apache-2.0")
	want := "-- SPDX-License-Identifier: Apache-2.0\n\nCREATE TABLE t (id int);\n"
	if string(out) != want {
		t.Errorf("InsertHeader SQL = %q, want %q", out, want)
	}
}

func TestWalk_DetectsMissingAndOK(t *testing.T) {
	dir := t.TempDir()
	mustWrite(t, filepath.Join(dir, "cmd", "gateway", "main.go"), "package main\n")
	mustWrite(t, filepath.Join(dir, "cmd", "gateway", "ok.go"), "// SPDX-License-Identifier: Apache-2.0\n\npackage main\n")
	mustWrite(t, filepath.Join(dir, "cmd", "node_modules", "y.go"), "package y\n") // excluded — must never appear
	mustWrite(t, filepath.Join(dir, "cmd", "gateway", "gen.go"), "// Code generated by sqlc. DO NOT EDIT.\npackage main\n")

	findings, err := Walk(dir)
	if err != nil {
		t.Fatalf("Walk: %v", err)
	}
	byPath := map[string]Finding{}
	for _, f := range findings {
		byPath[f.Path] = f
	}
	if byPath["cmd/gateway/main.go"].Status != "missing" {
		t.Errorf("main.go status = %q, want missing", byPath["cmd/gateway/main.go"].Status)
	}
	if byPath["cmd/gateway/ok.go"].Status != "ok" {
		t.Errorf("ok.go status = %q, want ok", byPath["cmd/gateway/ok.go"].Status)
	}
	if byPath["cmd/gateway/gen.go"].Status != "generated-skip" {
		t.Errorf("gen.go status = %q, want generated-skip", byPath["cmd/gateway/gen.go"].Status)
	}
	if _, found := byPath["cmd/node_modules/y.go"]; found {
		t.Error("excluded-directory file must never be visited/reported")
	}
}

func TestFix_InsertsOnlyMissing(t *testing.T) {
	dir := t.TempDir()
	mustWrite(t, filepath.Join(dir, "cmd", "gateway", "main.go"), "package main\n")

	findings, err := Walk(dir)
	if err != nil {
		t.Fatalf("Walk: %v", err)
	}
	n, err := Fix(dir, findings)
	if err != nil {
		t.Fatalf("Fix: %v", err)
	}
	if n != 1 {
		t.Fatalf("Fix inserted %d headers, want 1", n)
	}
	data, err := os.ReadFile(filepath.Join(dir, "cmd", "gateway", "main.go"))
	if err != nil {
		t.Fatal(err)
	}
	if !HasHeader(data, "// SPDX-License-Identifier: Apache-2.0") {
		t.Errorf("fixed file missing expected header:\n%s", data)
	}

	// Re-walking must now report it as "ok", never "missing" again.
	findings2, err := Walk(dir)
	if err != nil {
		t.Fatalf("Walk after fix: %v", err)
	}
	for _, f := range findings2 {
		if f.Path == "cmd/gateway/main.go" && f.Status != "ok" {
			t.Errorf("after Fix, status = %q, want ok", f.Status)
		}
	}
}

func mustWrite(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}
