-- SPDX-License-Identifier: Apache-2.0

-- Assignment time semantics: the inclusive-inclusive
-- date model cannot express a same-day handover — ending Alice today leaves her holder-of-record
-- TODAY, so the GiST exclusion constraint blocks Bob from starting today too. org.position_assignment
-- moves to HALF-OPEN ranges: valid_to becomes EXCLUSIVE (daterange(valid_from, valid_to, '[)') in
-- the exclusion constraint). The CHECK constraint already permits valid_to = valid_from and needs
-- no change: under `[)` that is an EMPTY range — no tenure at all (never returned by
-- GetAssignmentOnDate, never blocks a successor), which is what end-NOW on the start day
-- produces.
--
-- Existing rows: valid_to = valid_to + 1 day (an inclusive end date D becomes an exclusive end
-- date D+1 — the calendar day it covers is unchanged). No production assignment data exists at
-- the time this migration is authored; the count guard below refuses the automatic
-- rewrite if an unexpectedly large number of closed assignments are found, rather than silently
-- reinterpreting a lot of history.
DO $$
DECLARE
    closed_count integer;
BEGIN
    SELECT count(*) INTO closed_count FROM org.position_assignment WHERE valid_to IS NOT NULL;
    IF closed_count > 1000 THEN
        RAISE EXCEPTION
            'org.position_assignment half-open migration: % existing closed assignment row(s) exceeds the 1000-row safety threshold — refusing the automatic valid_to+1 rewrite; review manually before proceeding',
            closed_count;
    END IF;
END $$;

-- Drop the exclusion constraint by its actual (Postgres-generated) name — never hand-typed, so
-- this migration doesn't depend on guessing the autogenerated identifier.
DO $$
DECLARE
    excl_name text;
BEGIN
    SELECT conname INTO excl_name
    FROM pg_constraint
    WHERE conrelid = 'org.position_assignment'::regclass AND contype = 'x';

    IF excl_name IS NULL THEN
        RAISE EXCEPTION 'org.position_assignment: no exclusion constraint found to replace';
    END IF;

    EXECUTE format('ALTER TABLE org.position_assignment DROP CONSTRAINT %I', excl_name);
END $$;

UPDATE org.position_assignment SET valid_to = valid_to + 1 WHERE valid_to IS NOT NULL;

ALTER TABLE org.position_assignment
    ADD CONSTRAINT position_assignment_no_overlap EXCLUDE USING gist (
        position_id WITH =,
        daterange(valid_from, valid_to, '[)') WITH &&
    );

---- create above / drop below ----

DO $$
DECLARE
    excl_name text;
BEGIN
    SELECT conname INTO excl_name
    FROM pg_constraint
    WHERE conrelid = 'org.position_assignment'::regclass AND contype = 'x';

    IF excl_name IS NOT NULL THEN
        EXECUTE format('ALTER TABLE org.position_assignment DROP CONSTRAINT %I', excl_name);
    END IF;
END $$;

-- An empty `[)` window (valid_to = valid_from — assigned and ended on the same day) has no
-- inclusive-inclusive equivalent: valid_to - 1 would violate the CHECK (valid_to >= valid_from)
-- and keeping it as-is would turn "no tenure" into a one-day tenure that collides with a
-- same-day successor under the `[]` exclusion constraint. Such rows are deleted (the audit rows
-- that recorded the assign/end pair remain).
DELETE FROM org.position_assignment WHERE valid_to = valid_from;

UPDATE org.position_assignment SET valid_to = valid_to - 1 WHERE valid_to IS NOT NULL;

ALTER TABLE org.position_assignment
    ADD CONSTRAINT position_assignment_position_id_valid_from_valid_to_excl EXCLUDE USING gist (
        position_id WITH =,
        daterange(valid_from, valid_to, '[]') WITH &&
    );
