// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identity

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditIdentityEvent struct {
	ID            int64              `json:"id"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	Actor         string             `json:"actor"`
	Action        string             `json:"action"`
	Subject       string             `json:"subject"`
	Payload       []byte             `json:"payload"`
	CorrelationID *string            `json:"correlation_id"`
}

type IdentityMfaPolicy struct {
	ID        pgtype.UUID        `json:"id"`
	Scope     string             `json:"scope"`
	SubjectID pgtype.UUID        `json:"subject_id"`
	Required  bool               `json:"required"`
	Method    *string            `json:"method"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type IdentityUserAccount struct {
	ID                pgtype.UUID        `json:"id"`
	KcSub             string             `json:"kc_sub"`
	Email             *string            `json:"email"`
	PreferredUsername *string            `json:"preferred_username"`
	Lifecycle         string             `json:"lifecycle"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type IdentityUserLoginObservation struct {
	UserID      pgtype.UUID        `json:"user_id"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	LastLoginIp *string            `json:"last_login_ip"`
}

type IdentityUserReadV struct {
	ID                pgtype.UUID `json:"id"`
	KcSub             string      `json:"kc_sub"`
	Email             *string     `json:"email"`
	PreferredUsername *string     `json:"preferred_username"`
	Lifecycle         string      `json:"lifecycle"`
}
