// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package identity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUserMfaPolicy = `-- name: DeleteUserMfaPolicy :execrows
DELETE FROM identity.mfa_policy WHERE scope = 'user' AND subject_id = $1
`

func (q *Queries) DeleteUserMfaPolicy(ctx context.Context, subjectID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserMfaPolicy, subjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGlobalMfaPolicy = `-- name: GetGlobalMfaPolicy :one
SELECT id, scope, subject_id, required, method, updated_at FROM identity.mfa_policy WHERE scope = 'global'
`

func (q *Queries) GetGlobalMfaPolicy(ctx context.Context) (IdentityMfaPolicy, error) {
	row := q.db.QueryRow(ctx, getGlobalMfaPolicy)
	var i IdentityMfaPolicy
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.SubjectID,
		&i.Required,
		&i.Method,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAccountByID = `-- name: GetUserAccountByID :one
SELECT id, kc_sub, email, preferred_username, lifecycle, created_at, updated_at FROM identity.user_account WHERE id = $1
`

func (q *Queries) GetUserAccountByID(ctx context.Context, id pgtype.UUID) (IdentityUserAccount, error) {
	row := q.db.QueryRow(ctx, getUserAccountByID, id)
	var i IdentityUserAccount
	err := row.Scan(
		&i.ID,
		&i.KcSub,
		&i.Email,
		&i.PreferredUsername,
		&i.Lifecycle,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAccountByKcSub = `-- name: GetUserAccountByKcSub :one
SELECT id, kc_sub, email, preferred_username, lifecycle, created_at, updated_at FROM identity.user_account WHERE kc_sub = $1
`

func (q *Queries) GetUserAccountByKcSub(ctx context.Context, kcSub string) (IdentityUserAccount, error) {
	row := q.db.QueryRow(ctx, getUserAccountByKcSub, kcSub)
	var i IdentityUserAccount
	err := row.Scan(
		&i.ID,
		&i.KcSub,
		&i.Email,
		&i.PreferredUsername,
		&i.Lifecycle,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserMfaPolicy = `-- name: GetUserMfaPolicy :one
SELECT id, scope, subject_id, required, method, updated_at FROM identity.mfa_policy WHERE scope = 'user' AND subject_id = $1
`

func (q *Queries) GetUserMfaPolicy(ctx context.Context, subjectID pgtype.UUID) (IdentityMfaPolicy, error) {
	row := q.db.QueryRow(ctx, getUserMfaPolicy, subjectID)
	var i IdentityMfaPolicy
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.SubjectID,
		&i.Required,
		&i.Method,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserAccountsWithMfaPolicy = `-- name: ListUserAccountsWithMfaPolicy :many
SELECT ua.id, ua.kc_sub, mp.required, mp.method
FROM identity.user_account ua
LEFT JOIN identity.mfa_policy mp ON mp.scope = 'user' AND mp.subject_id = ua.id
ORDER BY ua.id
`

type ListUserAccountsWithMfaPolicyRow struct {
	ID       pgtype.UUID `json:"id"`
	KcSub    string      `json:"kc_sub"`
	Required *bool       `json:"required"`
	Method   *string     `json:"method"`
}

// Drives SyncMfaPolicy: every user plus their effective policy inputs (global row's
// required/method come back on every call the store layers in Go, not here).
func (q *Queries) ListUserAccountsWithMfaPolicy(ctx context.Context) ([]ListUserAccountsWithMfaPolicyRow, error) {
	rows, err := q.db.Query(ctx, listUserAccountsWithMfaPolicy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserAccountsWithMfaPolicyRow
	for rows.Next() {
		var i ListUserAccountsWithMfaPolicyRow
		if err := rows.Scan(
			&i.ID,
			&i.KcSub,
			&i.Required,
			&i.Method,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGlobalMfaPolicy = `-- name: SetGlobalMfaPolicy :exec
UPDATE identity.mfa_policy
SET required = $1, method = $2, updated_at = now()
WHERE scope = 'global'
`

type SetGlobalMfaPolicyParams struct {
	Required bool    `json:"required"`
	Method   *string `json:"method"`
}

func (q *Queries) SetGlobalMfaPolicy(ctx context.Context, arg SetGlobalMfaPolicyParams) error {
	_, err := q.db.Exec(ctx, setGlobalMfaPolicy, arg.Required, arg.Method)
	return err
}

const upsertUserAccount = `-- name: UpsertUserAccount :one


INSERT INTO identity.user_account (kc_sub, email, preferred_username)
VALUES ($1, $2, $3)
ON CONFLICT (kc_sub) DO UPDATE SET
    email = EXCLUDED.email,
    preferred_username = EXCLUDED.preferred_username,
    updated_at = now()
RETURNING id, kc_sub, email, preferred_username, lifecycle, created_at, updated_at
`

type UpsertUserAccountParams struct {
	KcSub             string  `json:"kc_sub"`
	Email             *string `json:"email"`
	PreferredUsername *string `json:"preferred_username"`
}

// SPDX-License-Identifier: Apache-2.0
// sqlc-generated queries for the identity service.
// Resolve-or-create: identity fields ONLY (never touches user_login_observation).
// Idempotent: calling twice with the same kc_sub returns the same row (id stable), refreshing
// email/preferred_username from the latest validated bearer claims.
func (q *Queries) UpsertUserAccount(ctx context.Context, arg UpsertUserAccountParams) (IdentityUserAccount, error) {
	row := q.db.QueryRow(ctx, upsertUserAccount, arg.KcSub, arg.Email, arg.PreferredUsername)
	var i IdentityUserAccount
	err := row.Scan(
		&i.ID,
		&i.KcSub,
		&i.Email,
		&i.PreferredUsername,
		&i.Lifecycle,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserMfaPolicy = `-- name: UpsertUserMfaPolicy :exec
INSERT INTO identity.mfa_policy (scope, subject_id, required, method)
VALUES ('user', $1, $2, $3)
ON CONFLICT (subject_id) WHERE scope = 'user' DO UPDATE SET
    required = EXCLUDED.required,
    method = EXCLUDED.method,
    updated_at = now()
`

type UpsertUserMfaPolicyParams struct {
	SubjectID pgtype.UUID `json:"subject_id"`
	Required  bool        `json:"required"`
	Method    *string     `json:"method"`
}

func (q *Queries) UpsertUserMfaPolicy(ctx context.Context, arg UpsertUserMfaPolicyParams) error {
	_, err := q.db.Exec(ctx, upsertUserMfaPolicy, arg.SubjectID, arg.Required, arg.Method)
	return err
}
